<main> ::= "init" ":" "{" [<declaration>] [<command>] "}"

<var> ::= <id> | (<id> "," <var>)

<declaration> ::= (<type> ":" <var> <end>) | (<type> ":" <var> <end> <declaration>)

<command> ::= (<allocation> <end> | <if> | <loop>) | (<allocation> <end> | <if> | <loop>) <command>

<allocation> ::= (<id> "=" (<id> | <number> | <operation> | <character> | <bool> | <bool_result> | <string>) | <id>"++" | <id>"--")

<type> ::= "integer" | "decimal" | "character" | "string" | "bool"

<operation> ::= (<id> | <number>) <op_symbol> (<id> | <number>)

<loop> ::= <loop> | <while>

<if> ::= "if" "(" <condition> ")" ":" "{" <command> "}" [<else>]

<else> ::= "else" ":" "{" <command> "}"

<loop> ::= "loop" "(" (<allocation> <end> | <end>) (<condition> <end> | <end>) [<allocation>] ")" ":" "{" <command> "}"

<while> ::= "while" "(" <condition> ")" ":" "{" <command> "}"

<condition> ::= (<bool_result>) | (<logic_symbol> <condition>)

<bool_result> ::= ["!"] (<id> | <bool> | <compare>) 

<compare_symbol> ::= ">" | "<" | ">=" | "<=" | "==" | "!="

<compare> ::= (<number> | <id>) <compare_symbol> (<number> | <id>) 

<logic_symbol> ::= "||" | "&&"

<end> ::= ";" 

<number> ::= 0..9+ | 0..9+"."0..9+ | "-"0..9+ | "-"0..9+"."0..9+

<id> ::= (a..z | _)(a..z | _ | 0..9)*

<operation_symbol> ::= "+" | "-" | "*" | "/" | "%"

<bool> ::= "true" | "false"

<string> ::= "\"" ... "\""

<digit_value> ::= 0..9

<character_value> ::= a..z | A..Z

<character> ::= "'" (<character_value> | <digit_value>) "'" 

<Keyword> ::= bool | case | character | double | without | loop | with | integer | while | init | string

/************    FIRST    ************/